- name: Add atom texteditor
  apt_repository:
    repo: ppa:webupd8team/atom
    update_cache: true

- name: Add canonical repository
  apt_repository:
    repo: deb http://archive.canonical.com/ precise partner
    update_cache: true
    state: present

- name: Install list of packages
  action: apt pkg={{item}} state=installed
  with_items:
   - keepass2
   - tmux
   - zsh
   - htop
   - guake
   - multitail
   - gedit
   - git
   - ack-grep
   - wget
   - curl
   - iotop
   - atop
   - ncdu
   - virtualbox
   #- adobereader-enu
   - atom
   - openssh-server
   - remmina
   - xrdp

- name: Remove canonical repository
  apt_repository:
    repo: deb http://archive.canonical.com/ precise partner
    state: absent

- name: Clone oh-my-zsh repo
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: "/home/{{ developmentUser }}/.oh-my-zsh"
  become_user: "{{ developmentUser }}"


- name: Copy .zshrc
  template: src=zsh.rc dest="/home/{{ developmentUser }}/.zshrc"


- name: Copy .tmux.conf
  template: src=.tmux.conf dest="/home/{{ developmentUser }}/.tmux.conf"

- name: Wget theme
  get_url:
    url: https://raw.githubusercontent.com/halfo/lambda-mod-zsh-theme/master/lambda-mod.zsh-theme
    dest: /home/{{ developmentUser }}/.oh-my-zsh/themes/lambda-mod.zsh-theme
    owner: "{{ developmentUser }}"
    group: "{{ developmentUser }}"
    mode: 0755


- name: Set zsh as default shell
  user: name="{{ developmentUser }}" shell=/bin/zsh

- name: Copy guake to autostart
  command: "cp /usr/share/applications/guake.desktop /etc/xdg/autostart/"


- name: download latest chrome
  get_url:
    url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dest: "/home/{{ developmentUser }}/chrome.deb"
    owner: "{{ developmentUser }}"
    group: "{{ developmentUser }}"

- name: install latest chrome
  apt:
    deb: "/home/{{ developmentUser }}/chrome.deb"
